# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: Quantum Original # Site title
  author: QOriginal Team # Author name
  url: https://blog.qoriginal.vip # Site url
  # Logo image (You can use local image, image external link or don’t fill)
  logo_img: /img/qo.png # logo image on the left of the navigation bar

# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#39C5BB"

  # Avatar (You can use local image or image external link)
  avatar: /img/qo.png # avatar of the author

  # Favicon (You can use local image or image external link)
  favicon: /img/server.jpg # favicon of the site

  # Article image align position
  article_img_align: center # value: left | center

  # Right side width
  right_side_width: 250px #sidebar width, for toc

  # Content area max width
  content_max_width: 1200px #content max width, for article

  #navigation bar background color (from left to right)
  nav_color: 
    left: "#66CCFF" #left side 
    right: "#99DD00"  #right side
    transparency: 35 #percent (10-99)

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: true # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_image:
      light: /img/background_light.png # background image of the first screen, use relative path or external link (if your website is in subdirectory, use external link)
      dark: /img/background_black.png # background image of the first screen, use relative path or external link (if your website is in subdirectory, use external link)
    title_color:
      light: "#fff" # first screen title color (light mode)
      dark: "#d1d1b6" # first screen title color (dark mode)
    description: "<h2 style='margin-block-end: 0;'>Quantum Original</h2><p style='margin-block-start: 0; font-size: 0.5em;'>做点有意义的事情</p>" # the title in the middle of the first screen. HTML supported (e.g. svg html code of your logo)

  # Scroll style settings
  scroll:
    progress_bar: # reading progress bar
      enable: true 
    percent: # reading progress percent
      enable: true

# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact: # social contact icons in the first screen, you can add more by using fontawesome icon names
  enable: true
  links:
    github:  # your GitHub URL
    instagram: # your Instagram URL
    zhihu:  # your ZhiHu URL
    twitter:  # your twitter URL
    email: hanserofficial@outlook.com # your email
    qq: https://jq.qq.com/?_wv=1027&k=NMZ0E9cD

# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu: #you can customize, i18n files are in the theme's languages folder. fa-regular recommended
  Home: 
    path: / 
    icon: fa-regular fa-house # can be empty
  Server Provider: 
    path: https://www.rhymc.com/
    icon: fa-solid fa-server # can be empty
  Notices: 
    path: https://blog.qoriginal.vip/2023/%E5%85%A5%E6%9C%8D%E9%A1%BB%E7%9F%A5/
    icon: fa-regular fa-link
  打赏页面: 
    path: http://qoriginal.vip:19333/files/zfb.jpg
    icon: fa-solid fa-money-bill
  # ...... # you can add more
custom_font: # custom font for the first screen
    enable: true
    font_family: apple # the font family name of the url below
    font_url: http:qoriginal.vip:19333/files/applefont.ttf # The url to the font file
# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  date_format: auto # date format in home page article block, value: auto | relative | YYYY-MM-DD | YYYY.MM.DD HH:mm:ss | DD/MM/YYYY | and etc. Support moment js format, see: https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 3 # max number of tags shown in home page article block

# ---------------------------------------------------------------------------------------
# Post page Settings
# ---------------------------------------------------------------------------------------
post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: true
    wordcount: true # word count, one article
    min2read: true # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: false # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: ["win"]

# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_block:
  copy: true # enable code copy button
  style: simple # mac | simple

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

  # If true, open TOC every time when you enter the article page
  init_open: true

# ---------------------------------------------------------------------------------------
# Post copyright info
# ---------------------------------------------------------------------------------------
copyright_info:
  enable: false

# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true

# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true
  preload: true # Preload the search data when the page loads

# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: false
  use: waline # values: waline | gitalk | twikoo

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:  # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html
  
  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: # GitHub repo owner
    repository: # Repository name to store issues
    client_id: # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    visitor: true
    env_id: # Vercel or Tencent Cloud Function environment ID
    region: # environment region. If select Guangzhou, fill in "ap-guangzhou". (optional)

# ---------------------------------------------------------------------------------------
# Friend Links page
# ---------------------------------------------------------------------------------------
friend_links:
  columns: 2 # number of columns. 2 or 3

# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false

# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: true

# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: false

# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: true

# ---------------------------------------------------------------------------------------
# Fontawesome
# ---------------------------------------------------------------------------------------
fontawesome: # select fontawesome versions you want to use, in order to reduce the loading time, select as few as possible
  thin: false # use fontawesome thin version or not
  light: false # use fontawesome light version or not
  duotone: false # use fontawesome duotone version or not

# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer:
  runtime: true # show website running time or not
  start_time: 2022/10/30 11:45:14 # the starting time of your website, format: yyyy/mm/dd hh:mm:ss
  customize: (c)2022-2023 Quantum Original # customize footer message, can be html code
  icp: # ICP record number of your website, Can be null

# ---------------------------------------------------------------------------------------
# Custom html code
# ---------------------------------------------------------------------------------------
inject:
  enable: false
  head: # inject code into <head> tag
    - 
    - 
  footer: # inject code into <footer> tag
    - 
    - 

# ---------------------------------------------------------------------------------------
# Redefine Theme version (Please dont modify it)
# Please go to github to update the latest version frequently
# Github: https://github.com/EvanNotFound/hexo-theme-redefine
# ---------------------------------------------------------------------------------------
version: 1.1.1
